dist: trusty
language: node_js
addons:
  chrome: stable
notifications:
  email: false
node_js: lts/*
stages:
  - test
jobs:
  include:
    - stage: test
      script:
        - npm run format:check
        - npm run lint
        - npm run test:ci
        - npm run build:prod
        - npm run test:report
      deploy:
        provider: script
        script: npm run semantic-release
        skip_cleanup: true
        keep_history: true
        on:
          tags: false
          all_branches: true
            condition: $TRAVIS_BRANCH =~ ^(master|next)$
